# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e60df792d7352b6b0bf8f0c510fef9d6018e0bef642e705c4ff9a95a60e207004491fb9f31fe2e95fefba795dcfd32df6360ecb56ea45a3078d10ba05ab2e56

test:
  secret_key_base: c75b9d3118aa4be078cbc6cfafdc0f60217df236b44b8000663d658608e70c96cdcc2f441b1cfdddf9cb98540d2bc323175df7f81454d17cd5e9ca9f861ae48f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
